---
title: "p3koa"
output: html_document
date: "2023-04-04"
---
```{r}
library(plyr)
library(dplyr)
library(tidyverse)
library(countrycode)
```

```{r}
happy = read.csv('/Users/averygoldberg/Desktop/DS 4002/hapiscore_whr.csv', header = TRUE)
```

```{r}
happy = happy[,c(1,4:19)] # includes only years 2006-2021
```

```{r}
names(happy) = c('country',2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021)
```

```{r}
# create data frame with country, year, score columns
newhappy = happy %>%
  gather(Year,Score,2:17)
```

```{r}
# convert year column to numeric values from character values
newhappy$Year = as.numeric(newhappy$Year)
# Remove NA values
newhappy = subset(newhappy, is.na(Score)==FALSE)
```

```{r}
# creates a linear model for each country
models <- dlply(newhappy, "country", function(df) 
  lm(Score ~ Year, data = df))

# returns coefficients of each linear model
fitted = ldply(models, coef)

# Linear Model source: https://stackoverflow.com/questions/1169539/linear-regression-and-group-by-in-r
perc = rep(NA, length(fitted$Slope))
names(fitted) = c('country','Intercept','Slope')
for (i in 1:length(fitted$Slope)) {
  expon = exp(fitted$Slope[i])
  min_one = expon-1
  fitted$perc[i] = 100*min_one
} # converts coefficient to percent change
```
SOMETHING IS WRONG HERE!!!!!!!!!!!
```{r}
fitted$continent <- countrycode(sourcevar = fitted[, "country"],
                            origin = "country.name",
                            destination = "continent")
# assigns continent to each country
```

```{r}
USperc = fitted[which(fitted$country == 'United States'),4]
```

```{r}
plot(newhappy$Year[which(newhappy$country == 'United States')],newhappy$Score[which(newhappy$country == 'United States')], xlab = 'Year', ylab = 'Happiness Score', main = 'Happiness Score vs Year for United States')
fit = lm(newhappy$Score[which(newhappy$country == 'United States')]~newhappy$Year[which(newhappy$country == 'United States')])
abline(fit)
```


```{r}
fitted$comp = NA
for (i in 1:length(fitted$perc)) {
  if (isTRUE(fitted$perc[i] >= USperc)) {
    fitted$comp[i] = "Less or Equal"
  } else {
    fitted$comp[i] = "More"
  }
}
```

```{r}
fitted %>% ggplot(aes(comp, fill = continent)) + geom_bar() + xlab('Percent Decrease Relative to United States') + ylab('Number of Countries') + labs(
  title = 'Number of Countries vs Percent Decrease in Happiness Score Relative to U.S.'
)
```


```{r}
less = 0
more = 0
for (i in 1:length(fitted$comp)) {
  if (fitted$comp[i] == 'Less or Equal') {
    less = less + 1
  } else {more = more + 1}
}
relative = c(more, less)
relative_name = c('more', 'less')
perc = data.frame((relative/162)*100,relative_name)
colnames(perc) = c('percent','Relative Percent Change')
rownames(perc) = c('more','less')
```

```{r}
ggplot(perc, aes(x = "", y = percent, fill = `Relative Percent Change`)) +
  geom_col() +
  geom_text(aes(label = paste(round(percent),'%',sep = "")),
            position = position_stack(vjust = 0.5)) +
  coord_polar(theta = "y")
```
